# Generated by Django 6.0.7 on 2026-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_paper_competition_starting_balance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='papercommodityorder',
            new_name='stocks_pape_user_id_5daead_idx',
            old_name='stocks_pape_user_id_c7d1f5_idx',
        ),
        migrations.RenameIndex(
            model_name='paperequitysnapshot',
            new_name='stocks_pape_user_id_b33a56_idx',
            old_name='stocks_pape_user_id_5e7f19_idx',
        ),
        migrations.RenameIndex(
            model_name='paperjournalentry',
            new_name='stocks_pape_user_id_141466_idx',
            old_name='stocks_pape_user_id_9c1d44_idx',
        ),
        migrations.RenameIndex(
            model_name='paperledgerentry',
            new_name='stocks_pape_user_id_8c7f3b_idx',
            old_name='stocks_pape_user_id_f3a8b2_idx',
        ),
        migrations.RenameIndex(
            model_name='paperoptionholding',
            new_name='stocks_pape_user_id_7d41aa_idx',
            old_name='stocks_pape_user_id_e1a7c1_idx',
        ),
        migrations.RenameIndex(
            model_name='paperoptionorder',
            new_name='stocks_pape_user_id_358ed3_idx',
            old_name='stocks_pape_user_id_f2b8d2_idx',
        ),
        migrations.RenameIndex(
            model_name='paperoptionorder',
            new_name='stocks_pape_user_id_8981eb_idx',
            old_name='stocks_pape_user_id_a9c3e4_idx',
        ),
        migrations.RenameIndex(
            model_name='paperorder',
            new_name='stocks_pape_user_id_09678e_idx',
            old_name='stocks_pape_user_id_1b6f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='paperorder',
            new_name='stocks_pape_status_7553a4_idx',
            old_name='stocks_pape_status_3d9c41_idx',
        ),
        migrations.RenameIndex(
            model_name='paperorder',
            new_name='stocks_pape_user_id_6cd36a_idx',
            old_name='stocks_pape_user_id_6a2e77_idx',
        ),
        migrations.AlterField(
            model_name='paperequitysnapshot',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperwallet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
