# Generated by Django 6.0.7 on 2026-07-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_rename_kyc_fnoelig_status_created_idx_kyc_fnoelig_status_25c40d_idx_and_more'),
    ]

    operations = [
        # 0005 already renamed these indexes at the database level (guarded — only if the
        # old name still existed). Re-running RenameIndex here would fail wherever 0005
        # already did its job, because the old-named index no longer exists. We only need
        # Django's migration *state* to catch up, so the DB side is a no-op.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='fnoeligibilityrequest',
                    new_name='kyc_fnoelig_status_25c40d_idx',
                    old_name='kyc_fnoelig_status_created_idx',
                ),
                migrations.RenameIndex(
                    model_name='kycrequest',
                    new_name='kyc_kycrequ_status_0d6aed_idx',
                    old_name='kyc_kycrequ_status_created_idx',
                ),
            ],
            database_operations=[],
        ),
    ]
