# Generated by Django 6.0.6 on 2026-07-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_rename_kyc_fnoelig_status_created_idx_kyc_fnoelig_status_25c40d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='aadhaar_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='aadhaar_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='aadhaar_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='aadhaar_dob',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='aadhaar_reference_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='aadhaar_failure_reason',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='aadhaar_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
